verbose: false
suppress:
  initial_userlist: false
  initial_topic: false
server:
  address: localhost
  port: 6667
  password:
  ssl: false
  webirc_password:
default:
  prefix:
  suffix:
  channels:
    - channel: '#minecraft'
	
autojoin: '#minecraft'
messages:
  chat-ingame: '[${PREFIX}${GROUP}${SUFFIX}&f] ${NICK}: ${MESSAGE}'
  chat-irc: '[${CHANNEL}] ${NICK}: ${MESSAGE}'
  quit: ${NICK} a quitté
  private: '${NICK}: ${MESSAGE}'
  part: ${NICK} est parti.
  rename: ${OLDNICK} est maintenant ${NEWNICK}
  kick: '${NICK} a été kické par ${OP}: ${REASON}'
  join: ${NICK} a rejoint IRC
  list: 'Sur IRC: ${LIST}'
  topic: '[${CHANNEL}] Topic modifié: ${TOPIC}'
  action: '* ${NICK} ${ACTION}'